{
 "title": "Unbound",
 "description": "Unbound metrics & logs dashboard using Prometheus and Loki",
 "tags": [
  "unbound",
  "prometheus",
  "loki",
  "dns"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 1, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "up{job=\"unbound\"}",
     "legendFormat": "Metrics"
    },
    {
     "expr": "scrape_duration_seconds{job=\"unbound\"}",
     "legendFormat": "Scrape"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_queries_total{job=\"unbound\"}",
     "legendFormat": "Total Queries"
    },
    {
     "expr": "unbound_cache_hits_total{job=\"unbound\"}",
     "legendFormat": "Cache Hits"
    },
    {
     "expr": "unbound_cache_misses_total{job=\"unbound\"}",
     "legendFormat": "Cache Miss"
    },
    {
     "expr": "unbound_prefetches_total{job=\"unbound\"}",
     "legendFormat": "Prefetch"
    },
    {
     "expr": "unbound_expired_total{job=\"unbound\"}",
     "legendFormat": "Expired"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_time_up_seconds_total{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "count(unbound_request_list_current_user{job=\"unbound\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_recursion_time_seconds_avg{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_request_list_current_all{job=\"unbound\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "unbound_request_list_avg{job=\"unbound\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 1, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_blocklist_domain_count{job=\"unbound\"}",
     "legendFormat": "Blocklist Domains"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_cache_hit_total{job=\"unbound\"}",
     "legendFormat": "hit"
    },
    {
     "expr": "unbound_cache_miss_total{job=\"unbound\"}",
     "legendFormat": "miss"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 7, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_query_udpout_count{job=\"unbound\"}",
     "legendFormat": "UDP Out"
    },
    {
     "expr": "unbound_query_tcpout_count{job=\"unbound\"}",
     "legendFormat": "TCP Out"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 11, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(unbound_memory_caches_bytes{job=\"unbound\"})",
     "legendFormat": "Cache Mem"
    },
    {
     "expr": "sum(unbound_memory_modules_bytes{job=\"unbound\"})",
     "legendFormat": "Modules Mem"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_msg_cache_count{job=\"unbound\"}",
     "legendFormat": "Msg Cache"
    },
    {
     "expr": "unbound_rrset_cache_count{job=\"unbound\"}",
     "legendFormat": "RRset Cache"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_infra_cache_count{job=\"unbound\"}",
     "legendFormat": "Infra Cache"
    },
    {
     "expr": "unbound_key_cache_count{job=\"unbound\"}",
     "legendFormat": "Key Cache"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 23, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  { "title": "⧉ Response Time Buckets", "type": "text", "gridPos": { "h": 1, "w": 8, "x": 0, "y": 6 } },
  { "title": "⧉ Recursion Time", "type": "text", "gridPos": { "h": 1, "w": 9, "x": 8, "y": 6 } },
  {
   "title": "⧉ Live Clients (per 30m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "count(\n  sum by (client) (\n    count_over_time(\n      {systemd_unit=\"unbound.service\"}\n      |~ \" info: [0-9A-Fa-f:.]+ \"\n      |~ \" IN \"\n      | pattern `<_> <_> <_> <_> <client> <_> <_> <_> <_> <_> <_> <_>`\n      [$__interval]\n    )\n  ) > 0\n)",
     "legendFormat": "{{client}}",
     "resolution": 1
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_response_time_seconds_bucket{job=\"unbound\"} > 0",
     "legendFormat": "{{lower}} - {{upper}}"
    }
   ]
  },
  {
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "unbound_recursion_time_seconds_avg{job=\"unbound\"}",
     "legendFormat": "Avg"
    },
    {
     "expr": "unbound_recursion_time_seconds_median{job=\"unbound\"}",
     "legendFormat": "Median"
    }
   ]
  },
  {
   "title": "⧉ Query Types",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_query_types_count{job=\"unbound\"} > 0",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "⧉ Response",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "unbound_answer_rcodes_count{job=\"unbound\"} > 0",
     "legendFormat": "{{rcode}}"
    },
    {
     "expr": "unbound_answer_secure_count{job=\"unbound\"} > 0",
     "legendFormat": "secure"
    },
    {
     "expr": "unbound_answer_bogus_count{job=\"unbound\"} > 0",
     "legendFormat": "bogus"
    }
   ]
  },
  {
   "title": "⧉ Queries",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {systemd_unit=\"unbound.service\"}\n    |~ \" info: [0-9A-Fa-f:.]+ \"\n    |~ \" IN \"\n    | pattern `<_> <_> <_> <client> <domain> <qtype> <_> <rcode> <_> <_> <_>`\n    [$__range]\n  )\n) or vector(0)"
    },
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {systemd_unit=\"unbound.service\"}\n    |~ \" info: [0-9A-Fa-f:.]+ \"\n    |~ \" IN (NXDOMAIN|REFUSED) \"\n    [$__range]\n  )\n) or vector(0)"
    }
   ]
  },
  {
   "title": "⧉ Queries (per 30m)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {systemd_unit=\"unbound.service\"}\n    |~ \" info: [0-9A-Fa-f:.]+ \"\n    |~ \" IN \"\n    | pattern `<_> <_> <_> <client> <domain> <qtype> <_> <rcode> <_> <_> <_>`\n    [$__interval]\n  )\n) or vector(0)",
     "legendFormat": "Allowed",
     "resolution": 1
    },
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {systemd_unit=\"unbound.service\"}\n    |~ \" info: [0-9A-Fa-f:.]+ \"\n    |~ \" IN (NXDOMAIN|REFUSED) \"\n    [$__interval]\n  )\n) or vector(0)",
     "legendFormat": "Blocked",
     "resolution": 1
    }
   ]
  },
  {
   "title": "⧉ Client Requests (per 30m)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  count_over_time(\n    {systemd_unit=\"unbound.service\"}\n    |~ \" info: [0-9A-Fa-f:.]+ \"\n    |~ \" IN \"\n    | pattern `<_> <_> <_> <client> <_> <_> <_> <_> <_> <_> <_>`\n    [$__interval]\n  )\n)",
     "legendFormat": "Requests",
     "resolution": 1
    }
   ]
  },
  {
   "title": "⧉ Top Client Queries",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(50,\n  label_replace(\n    sum by (domain, client) (\n      count_over_time(\n        {systemd_unit=\"unbound.service\"}\n        |~ \" info: [0-9A-Fa-f:.]+ \"\n        |~ \" IN \"\n        | pattern `<_> info: <client> <domain> <qtype> IN <_> <_> <_> <_>`\n        [$__range]\n      )\n    ),\n    \"domain\", \"$1\", \"domain\", \"^(.*)\\\\.$\"\n  )\n)\n"
    }
   ]
  },
  {
   "title": "⧉ Top Blocked",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 26 },
   "targets": [
    {
     "direction": "backward",
     "expr": "topk(50,\n  label_replace(\n    sum by (domain) (\n      count_over_time(\n        {systemd_unit=\"unbound.service\"}\n        |~ \" info: [0-9A-Fa-f:.]+ \"\n        |~ \" IN (NXDOMAIN|REFUSED) \"\n        | regexp `info:\\s+(?P<client>[0-9A-Fa-f:.]+)\\s+(?P<domain>\\S+)\\s+(?P<qtype>\\S+)\\s+IN\\s+(?P<rcode>\\S+)`\n        [$__range]\n      )\n    ),\n    \"domain\", \"$1\", \"domain\", \"^(.*)\\\\.$\"\n  )\n)\n"
    }
   ]
  },
  {
   "title": "⧉ Live Queries",
   "type": "table",
   "gridPos": { "h": 12, "w": 13, "x": 0, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{systemd_unit=\"unbound.service\"}\n|~ \" info: [0-9A-Fa-f:.]+ \"\n|~ \" IN \"\n| regexp `info:\\s+(?P<Client>[0-9A-Fa-f:.]+)\\s+(?P<Domain>\\S+)\\s+(?P<Type>\\S+)\\s+IN\\s+(?P<Reply>\\S+)\\s+(?P<Lookup>[0-9.]+)\\s+(?P<Cache>[01])\\s+.*$`\n| line_format `{{.Domain}} {{.Client}} {{.Reply}} {{.Lookup}} {{.Type}}`\n"
    }
   ]
  },
  {
   "title": "⧉ Live Blocked",
   "type": "table",
   "gridPos": { "h": 12, "w": 11, "x": 13, "y": 38 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{systemd_unit=\"unbound.service\"}\n|~ \" info: [0-9A-Fa-f:.]+ \"\n|~ \" IN (NXDOMAIN|REFUSED) \"\n| regexp `info:\\s+(?P<Client>[0-9A-Fa-f:.]+)\\s+(?P<Domain>\\S+)\\s+\\S+\\s+IN\\s+(?P<Reply>NXDOMAIN|REFUSED)\\s+.*$`\n| line_format `{{.Domain}} {{.Client}} {{.Reply}}`"
    }
   ]
  }
 ]
}