# General bindigs

abbr --add --global g 'git'
abbr --add --global py 'python'

# PHP related

abbr --add --global art 'php artisan'
abbr --add --global comp 'composer'

# Git related stuff

abbr --add --global gs 'git status'
abbr --add --global gb 'git branch'
abbr --add --global gf 'git fetch'
abbr --add --global gfo 'git fetch origin'
abbr --add --global gc 'git commit'
abbr --add --global gch 'git checkout'
abbr --add --global gchb 'git checkout -b'
abbr --add --global gcl 'git clone'
abbr --add --global gph 'git push'
abbr --add --global gphf 'git push --force'
abbr --add --global gphu 'git push --set-upstream'
abbr --add --global gphuo 'git push --set-upstream origin'
abbr --add --global gphuof 'git push --set-upstream --force origin'
abbr --add --global gpl 'git pull'
abbr --add --global gplf 'git pull --force'
abbr --add --global gplo 'git pull origin'
abbr --add --global gplof 'git pull origin --force'
abbr --add --global ga 'git add'
abbr --add --global gaa 'git add *'
abbr --add --global gr 'git reset'
abbr --add --global grh 'git reset HEAD'
abbr --add --global grha 'git reset HEAD *'
abbr --add --global gs 'git status'
abbr --add --global gsh 'git stash'
abbr --add --global gsha 'git stash apply'
abbr --add --global grm 'git rm'
abbr --add --global grmc 'git rm --cached'
abbr --add --global gm 'git merge'
abbr --add --global gmf 'git merge --force'
abbr --add --global gi 'git init'
abbr --add --global gd 'git diff'
abbr --add --global gl 'git log'
abbr --add --global gll 'git lg3-specific --all'
