{
 "title": "Rspamd stat overview by tsandrini",
 "description": "Rspamd export stats in the openmetrics format that can be read by Prometheus.\r\nThis dashboard displays Rspamd stats collected using Prometheus.",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(rspamd_total_learns,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sys Info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{instance=\"$instance\"}",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_connections{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Control connections",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_control_connections{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_bytes_allocated{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Scanned",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_scanned{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scanned messages",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 3, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_ham_count{instance=\"$instance\"}",
     "legendFormat": "HAM"
    },
    {
     "expr": "rspamd_spam_count{instance=\"$instance\"}",
     "legendFormat": "SPAM"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 10, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_chunks_allocated{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rspamd_chunks_freed{instance=\"$instance\"}",
     "legendFormat": "Freed"
    },
    {
     "expr": "rspamd_shared_chunks_allocated{instance=\"$instance\"}",
     "legendFormat": "Shared Allocated"
    },
    {
     "expr": "rspamd_chunks_oversized{instance=\"$instance\"}",
     "legendFormat": "Oversized"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 17, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_pools_allocated{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rspamd_pools_freed{instance=\"$instance\"}",
     "legendFormat": "Freed"
    }
   ]
  },
  {
   "title": "Learn",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_total_learns{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  { "title": "Actions", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "No action",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_no_action{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Soft Reject",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_soft_reject{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Reject",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_reject{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Greylist",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_greylist{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Rewrite subject",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_rewrite_subject{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Add header",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rspamd_actions_add_header{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Action rates",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "rate(rspamd_actions_no_action{instance=\"$instance\"}[2m])",
     "legendFormat": "no_action"
    },
    {
     "expr": "rate(rspamd_actions_rewrite_subject{instance=\"$instance\"}[2m])",
     "legendFormat": "rewrite_subject"
    },
    {
     "expr": "rate(rspamd_actions_reject{instance=\"$instance\"}[2m])",
     "legendFormat": "reject"
    },
    {
     "expr": "rate(rspamd_actions_add_header{instance=\"$instance\"}[2m])",
     "legendFormat": "add_header"
    },
    {
     "expr": "rate(rspamd_actions_greylist{instance=\"$instance\"}[2m])",
     "legendFormat": "greylist"
    },
    {
     "expr": "rate(rspamd_actions_soft_reject{instance=\"$instance\"}[2m])",
     "legendFormat": "soft_reject"
    }
   ]
  },
  {
   "title": "SPAM/HAM rates",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 20 },
   "targets": [
    {
     "expr": "rate(rspamd_spam_count{instance=\"$instance\"}[2m])",
     "legendFormat": "SPAM"
    },
    {
     "expr": "rate(rspamd_ham_count{instance=\"$instance\"}[2m])",
     "legendFormat": "HAM"
    },
    {
     "expr": "rate(rspamd_scanned_total{instance=\"$instance\"}[2m])",
     "legendFormat": "Scanned"
    }
   ]
  },
  {
   "title": "Chunks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rspamd_chunks_allocated{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rspamd_chunks_freed{instance=\"$instance\"}",
     "legendFormat": "Freed"
    },
    {
     "expr": "rspamd_shared_chunks_allocated{instance=\"$instance\"}",
     "legendFormat": "Shared Allocated"
    },
    {
     "expr": "rspamd_chunks_oversized{instance=\"$instance\"}",
     "legendFormat": "Oversized"
    }
   ]
  },
  {
   "title": "Pools",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rspamd_pools_allocated{instance=\"$instance\"}",
     "legendFormat": "Allocated"
    },
    {
     "expr": "rspamd_pools_freed{instance=\"$instance\"}",
     "legendFormat": "Freed"
    }
   ]
  }
 ]
}