[Configuration]
FontName=Menlo for Powerline 12
MiscAlwaysShowTabs=FALSE
MiscBell=FALSE
MiscBellUrgent=FALSE
MiscBordersDefault=FALSE
MiscCursorBlinks=TRUE
MiscCursorShape=TERMINAL_CURSOR_SHAPE_UNDERLINE
MiscDefaultGeometry=80x24
MiscInheritGeometry=FALSE
MiscMenubarDefault=FALSE
MiscMouseAutohide=FALSE
MiscMouseWheelZoom=TRUE
MiscToolbarDefault=FALSE
MiscConfirmClose=TRUE
MiscCycleTabs=TRUE
MiscTabCloseButtons=TRUE
MiscTabCloseMiddleClick=TRUE
MiscTabPosition=GTK_POS_TOP
MiscHighlightUrls=TRUE
MiscMiddleClickOpensUri=FALSE
MiscCopyOnSelect=FALSE
MiscDefaultWorkingDir=
MiscRewrapOnResize=TRUE
MiscUseShiftArrowsToScroll=FALSE
MiscSlimTabs=FALSE
BackgroundMode=TERMINAL_BACKGROUND_TRANSPARENT
BackgroundDarkness=0,800000
ScrollingBar=TERMINAL_SCROLLBAR_NONE
ColorPalette={{ primary }};{{ secondary }};{{ tertiary }};{{ special }};{{ black }};{{ white }}
ColorForeground={{ special }}
ColorBackground={{ tertiary }}
ColorCursor={{ special }}
ColorBold={{ tertiary }}
ColorBoldUseDefault=FALSE
TabActivityColor=#dc322f
TitleMode=TERMINAL_TITLE_HIDE
