name: "Run various checks on merge (pull) request"

on:
  # push: # TODO temporary just for testing
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Setup Nix
      #   uses: DeterminateSystems/nix-installer-action@main

      # - name: Check formatting
      #   run: nix-shell -p nixfmt --command "find . -name '*.nix' -type f -exec nixfmt -c {} +"

      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest

      - name: Build the devenv shell and run any pre-commit hooks
        run: devenv ci

      - name: Check the flake
        run: nix flake check --impure --show-trace --all-systems
