name: "Run various checks on merge (pull) request"

on:
  push: # TODO temporary just for testing
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
      - uses: cachix/cachix-action@v12
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install tarball+https://install.devenv.sh/latest

      - name: Pre-commit checks
        run: nix develop .#devenv --impure --command "pre-commit run --all-files"

      - name: Check the flake
        run: nix develop .#devenv --impure --command "nix flake check --impure --show-trace --all-systems"
