name: "Run various checks on merge (pull) request"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4

      - name: Complete nix setup
        uses: DeterminateSystems/nix-installer-action@main

      - name: pre-commit checks
        run: nix develop .#devenv --impure --command bash -c "pre-commit run --all-files"

      - name: Check the flake
        run: nix develop .#devenv --impure --command bash -c "nix flake check --impure --show-trace"
        # TODO this would be a great addition to update in the future, right now
        # some minor stuff isn't passing, but I don't have the time to
        # emulate all other platforms that I don't care about at the moment
        # run: nix develop .#devenv --impure --command bash -c "nix flake check --impure --show-trace --all-systems"
