name: "FlakeHub"
on:
  push:
    branches:
      - "null"
jobs:
  flakehub-publish:
    runs-on: "ubuntu-latest"
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - uses: DeterminateSystems/flakehub-push@main
        with:
          name: "tsandrini/tensorfiles"
          rolling: true
          visibility: "public"
